//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightReservation
    {
        public int reservationId { get; set; }
        public int membershipId { get; set; }
        public int flightId { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public string seat { get; set; }
        public decimal price { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Membership Membership { get; set; }
    }
}
