//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.FlightReservations = new HashSet<FlightReservation>();
        }
    
        public int FlightID { get; set; }
        public string FlightNumber { get; set; }
        public string DepartureCountry { get; set; }
        public string ArrivalCountry { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public bool IsTransfer { get; set; }
        public Nullable<int> transferId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightReservation> FlightReservations { get; set; }
        public virtual CountryCode CountryCode { get; set; }
        public virtual CountryCode CountryCode1 { get; set; }
        public virtual TransferFlight TransferFlight { get; set; }
    }
}
