//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelReservation
    {
        public int reservationId { get; set; }
        public int hotelId { get; set; }
        public int membershipId { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int days { get; set; }
        public int rooms { get; set; }
        public decimal cost { get; set; }
        public string comment { get; set; }
    
        public virtual HotelCountry HotelCountry { get; set; }
        public virtual Membership Membership { get; set; }
    }
}
