//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageReservation
    {
        public int id { get; set; }
        public int packageId { get; set; }
        public System.DateTime date { get; set; }
        public int noOfParticipants { get; set; }
        public decimal totalCost { get; set; }
        public int membershipId { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual Package Package { get; set; }
    }
}
