//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantReservation
    {
        public int id { get; set; }
        public int restaurantId { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public int seats { get; set; }
        public int membershipId { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
