//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleId { get; set; }
        public int packageId { get; set; }
        public string name { get; set; }
        public System.DateTime startingDate { get; set; }
        public System.DateTime endingDate { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
